import os
import glob
from pathlib import Path

def clear_clustering_cache():
    # 1. Define the target directory
    # Adjust this if your folder name is different, but based on your ls it is 'pdb_train'
    target_dir = Path("data/pdb_train")
    
    if not target_dir.exists():
        print(f"❌ Directory not found: {target_dir}")
        return

    # 2. Define patterns for cache files
    # These match the files generated by PDBDataSplitter in pdb_data.py
    patterns = [
        "cluster_seqid_*.tsv",   # The cluster mapping (CRITICAL to delete)
        "cluster_seqid_*.fasta", # The cluster representatives
        "seq_df_pdb_*.fasta"     # The extracted sequences from the old CSV
    ]

    files_to_delete = []
    for pattern in patterns:
        files_to_delete.extend(list(target_dir.glob(pattern)))

    # 3. Safety Check
    if not files_to_delete:
        print("✅ No cache files found! You are good to go.")
        return

    print(f"⚠️  Found {len(files_to_delete)} cache files to delete in {target_dir}:")
    for f in files_to_delete:
        print(f"  - {f.name}")

    # 4. Delete
    confirm = input("\nType 'yes' to delete these files: ")
    if confirm.lower() == "yes":
        for f in files_to_delete:
            try:
                os.remove(f)
                print(f"🗑️  Deleted: {f.name}")
            except Exception as e:
                print(f"❌ Error deleting {f.name}: {e}")
        print("\n✨ Done! Now run your training script again.")
    else:
        print("❌ Operation cancelled.")

if __name__ == "__main__":
    clear_clustering_cache()