import os
import torch
import glob
from tqdm import tqdm
from torch_geometric.transforms import Compose
from torch.utils.data import Dataset, DataLoader

# Official project imports
from proteinfoundation.partial_autoencoder.autoencoder import AutoEncoder
from proteinfoundation.datasets.transforms import (
    CoordsToNanometers, 
    CenterStructureTransform, 
    ChainBreakCountingTransform
)
from proteinfoundation.utils.constants import PDB_TO_OPENFOLD_INDEX_TENSOR

# ==============================================================================
# CONFIGURATION
# ==============================================================================
FORCE_RECOMPUTE = False
NUM_WORKERS = 16
BATCH_SIZE = 1
DEV = False
FOLDING_MODE_ENABLED = True

# Optional: path to a metadata CSV (as generated by PDBDataSelector) whose `pdb`/`chain`
# columns define which proteins to encode. Set to None to process all files in DATA_DIR.
# Example: "/home/ks2218/la-proteina/data/pdb_train/df_pdb_f1_minl50_maxl200_...rnsrTrue_rpuFalse_l_rcuFalse.csv"
FILTER_CSV = "/home/ks2218/la-proteina/data/pdb_train/df_pdb_f1_minl50_maxl200_mtprotein_etdiffractionEM_minoNone_maxoNone_minr0.0_maxr5.0_hl_rl_rnsrTrue_rpuFalse_l_rcuFalse.csv"

if DEV:
    DATA_DIR = "/home/ks2218/la-proteina/data/pdb_train/processed"
    OUT_DIR = "/home/ks2218/la-proteina/data/pdb_train/processed_latents"
    AE_PATH = "/home/ks2218/la-proteina/checkpoints_laproteina/AE1_ucond_512.ckpt"



else:
    DATA_DIR = "/rds/user/ks2218/hpc-work/processed"
    OUT_DIR = "/rds/user/ks2218/hpc-work/processed_latents"
    AE_PATH = "/rds/user/ks2218/hpc-work/checkpoints_laproteina/AE1_ucond_512.ckpt"

class ProteinDataset(Dataset):
    """Dataset to handle CPU-side loading and baking in parallel workers."""
    def __init__(self, files, data_dir, out_dir, baking_pipeline):
        self.files = files
        self.data_dir = data_dir
        self.out_dir = out_dir
        self.baking_pipeline = baking_pipeline

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        f = self.files[idx]
        rel_path = os.path.relpath(f, self.data_dir)
        out_path = os.path.join(self.out_dir, rel_path)
        
        if os.path.exists(out_path) and not FORCE_RECOMPUTE:
            return None, out_path

        try:
            data = torch.load(f, map_location='cpu', weights_only=False)
            
            # Determine true length L from the mask
            L_true = data.coord_mask.shape[0]
            
            for key in data.keys():
                val = data[key]
                if torch.is_tensor(val) and val.ndim > 0 and val.shape[0] > L_true:
                    data[key] = val[:L_true]
                    
            # Standardize Atom Order
            data.coords = data.coords[:, PDB_TO_OPENFOLD_INDEX_TENSOR, :]
            data.coord_mask = data.coord_mask[:, PDB_TO_OPENFOLD_INDEX_TENSOR]
            
            # Apply Baking Pipeline
            data = self.baking_pipeline(data)
            
            return data, out_path
        except Exception as e:
            print(f"\n[WORKER FAILURE] {f}: {e}")
            return None, out_path
        
def main():
    assert os.path.exists(DATA_DIR), f"Source data directory missing: {DATA_DIR}"
    assert os.path.exists(AE_PATH), f"AutoEncoder checkpoint missing: {AE_PATH}"
    
    print(f"Loading AutoEncoder from {AE_PATH}...")
    ae = AutoEncoder.load_from_checkpoint(AE_PATH).cuda().eval()
    
    assert hasattr(ae, 'latent_dim'), "AutoEncoder missing 'latent_dim' property."
    print(f"AutoEncoder verified. Latent dimension: {ae.latent_dim}")
    
    baking_pipeline = Compose([
        CoordsToNanometers(),
        CenterStructureTransform(),
        ChainBreakCountingTransform(),
    ])
    
    files = glob.glob(os.path.join(DATA_DIR, "**", "*.pt"), recursive=True)
    print(f"Found {len(files)} source files in DATA_DIR.")

    if FILTER_CSV is not None:
        import pandas as pd
        assert os.path.exists(FILTER_CSV), f"FILTER_CSV not found: {FILTER_CSV}"
        df = pd.read_csv(FILTER_CSV)
        # Build set of expected filenames (e.g. "1abc_A" or "1abc")
        allowed = set()
        for _, row in df.iterrows():
            pdb = str(row["pdb"]).lower()
            chain = row.get("chain", None)
            if chain is not None and str(chain) not in ("nan", "all", ""):
                allowed.add(f"{pdb}_{chain}")
            else:
                allowed.add(pdb)
        # Filter to only files whose stem is in the allowed set
        files = [f for f in files if os.path.splitext(os.path.basename(f))[0] in allowed]
        print(f"Filtered to {len(files)} files matching FILTER_CSV ({FILTER_CSV}).")
    else:
        print("No FILTER_CSV set — processing all files.")

    print(f"Starting computation on {len(files)} files...")

    dataset = ProteinDataset(files, DATA_DIR, OUT_DIR, baking_pipeline)
    loader = DataLoader(
        dataset, 
        batch_size=BATCH_SIZE, 
        num_workers=NUM_WORKERS,
        pin_memory=True,
        collate_fn=lambda x: x[0] 
    )

    with torch.no_grad():
        for data, out_path in tqdm(loader, desc="Precomputing"):
            if data is None:
                continue

            try:
                L = data.coord_mask.shape[0]
                assert L > 0, f"[{out_path}] Empty protein detected (L=0)"
                
                # Prune any remaining metadata that is longer than L
                for key in ['residue_pdb_idx', 'seq_pos', 'residue_type', 'bfactor', 'aatype']:
                    if hasattr(data, key):
                        val = getattr(data, key)
                        if hasattr(val, 'shape') and val.shape[0] > L:
                            setattr(data, key, val[:L])

                # D. Build an ISOLATED dictionary for the Encoder (prevents mutating 'data')
                encoder_input = {}
                for k in data.keys():
                    val = data[k]
                    if isinstance(val, torch.Tensor):
                        # Move to GPU and add batch dimension [1, ...]
                        encoder_input[k] = val.to('cuda', non_blocking=True).unsqueeze(0)
                    else:
                        encoder_input[k] = val

                na_idx = 0
                seq_mask = encoder_input["coord_mask"][:, :, na_idx].bool() 

                encoder_input["mask_dict"] = {
                    "coords": seq_mask.unsqueeze(-1).unsqueeze(-1), 
                    "residue_type": seq_mask
                }
                encoder_input["mask"] = seq_mask

                # E. Run Encoder to get latents
                output_enc = ae.encoder(encoder_input)
                
                # Extract first item from batch
                mean = output_enc["mean"][0] 
                log_scale = output_enc["log_scale"][0]
                
                # --- SHAPE ALIGNMENT FIX ---
                if mean.shape[1] == L and mean.shape[0] == ae.latent_dim:
                    mean = mean.transpose(0, 1)
                    log_scale = log_scale.transpose(0, 1)

                # --- CRITICAL SEQUENCE LENGTH ASSERTION ---
                assert mean.shape[0] == L, \
                    f"[{out_path}] CRITICAL: Encoder output length ({mean.shape[0]}) mismatch with mask length ({L})"
                assert mean.shape[1] == ae.latent_dim, \
                    f"[{out_path}] Latent dim mismatch: expected {ae.latent_dim}, got {mean.shape[1]}"

                # Assign latents to the CLEAN CPU data object
                data.mean = mean.cpu()
                data.log_scale = log_scale.cpu()
                
                # F. Optimization: Delete unscaled Angstrom coords
                if hasattr(data, 'coords'):
                    del data.coords
                
                # Final check: Since data was never unsqueezed, this will be strictly L == L
                assert data.mean.shape[0] == data.coord_mask.shape[0], \
                    f"Final check failed: mean {data.mean.shape} != mask {data.coord_mask.shape}"
                
                keys_to_keep = ['mean', 'log_scale', 'coords_nm', 'coord_mask', 'id']
                if  (FOLDING_MODE_ENABLED): # Only keep if doing folding iters
                    keys_to_keep += ['residue_type', 'bb_ca'] 

                for key in list(data.keys()):
                    if key not in keys_to_keep:
                        del data[key]
                os.makedirs(os.path.dirname(out_path), exist_ok=True)
                tmp_path = out_path + ".tmp"
                torch.save(data, tmp_path)
                os.rename(tmp_path, out_path)  # atomic: prevents partial files if job is killed mid-write

            except Exception as e:
                print(f"\n[GPU FAILURE] {out_path}: {e}")

    print(f"\n--- Precomputation Complete ---")

if __name__ == "__main__":
    main()