#!/bin/bash
# Hybrid designability probe driver. CRITICAL: uses generate_hybrid.py,
# NOT generate.py — the latter silently ignores ckpt_path_a/b, ckpt_name_a/b,
# t_switch keys and runs single-model from ckpt_name only (= the conv A-ckpt
# in the existing hybrid YAMLs). All three nfe400 hybrid CSVs on disk from
# 2026-05-07 were generated by that broken driver and are conv-alone artifacts,
# not hybrid runs — see E087 in experiments.md.
#
# Usage: CUDA_VISIBLE_DEVICES=<n> bash probe_hybrid_nfe400.sh <config_name>
# Example: CUDA_VISIBLE_DEVICES=6 bash probe_hybrid_nfe400.sh inference_hybrid_conv_to_canonical_t06_n6_nfe400

set -uo pipefail
cd /home/ks2218/la-proteina

export PYTHON_EXEC=/home/ks2218/.conda/envs/laproteina_env/bin/python
export PATH=/home/ks2218/.conda/envs/laproteina_env/bin:$PATH

CFG=${1:?usage: probe_hybrid_nfe400.sh <config_name>}
GPU=${CUDA_VISIBLE_DEVICES:-0}
LOGBASE=/home/ks2218/la-proteina/nohup_${CFG}

# Make sure stale CSV / output dir from the buggy 2026-05-07 conv-alone run
# don't fool generate_hybrid.py's "skip if results exist" guard (line 55-57).
CSV_PATH=/home/ks2218/la-proteina/inference/results_${CFG}_0.csv
OUT_DIR=/home/ks2218/la-proteina/inference/${CFG}
if [ -f "$CSV_PATH" ]; then
    echo "[$(date)] [GPU $GPU] Moving stale CSV to ${CSV_PATH}.preE087_buggy"
    mv "$CSV_PATH" "${CSV_PATH}.preE087_buggy"
fi
if [ -d "$OUT_DIR" ]; then
    echo "[$(date)] [GPU $GPU] Moving stale output dir to ${OUT_DIR}.preE087_buggy"
    mv "$OUT_DIR" "${OUT_DIR}.preE087_buggy"
fi

echo "[$(date)] [GPU $GPU] === HYBRID probe start: $CFG ==="
echo "[$(date)] [GPU $GPU] gen (generate_hybrid.py) → ${LOGBASE}.gen.log"
CUDA_VISIBLE_DEVICES=$GPU $PYTHON_EXEC proteinfoundation/generate_hybrid.py \
    --config-name=$CFG > "${LOGBASE}.gen.log" 2>&1
GENRC=$?
echo "[$(date)] [GPU $GPU] gen exit=$GENRC"
if [ $GENRC -ne 0 ]; then
    echo "[$(date)] gen failed — last 30 lines of ${LOGBASE}.gen.log:"
    tail -30 "${LOGBASE}.gen.log"
    exit $GENRC
fi

echo "[$(date)] [GPU $GPU] hybrid canaries (MUST see Hybrid sampling + kink):"
grep -E "Hybrid sampling|hybrid kink|hybrid canary|model_[AB]\.run_name" "${LOGBASE}.gen.log" | head -8 || \
    echo "  ** WARNING: NO hybrid canary found — this is the E087 bug! **"

GENDIR=/home/ks2218/la-proteina/inference/${CFG}
if [ -d "$GENDIR" ]; then
    for d in "$GENDIR"/job_0_n_*_id_*; do
        [ -d "$d/$(basename "$d")" ] && rm -rf "$d/$(basename "$d")"
    done
fi

echo "[$(date)] [GPU $GPU] eval → ${LOGBASE}.eval.log"
CUDA_VISIBLE_DEVICES=$GPU $PYTHON_EXEC proteinfoundation/evaluate.py \
    --config_name $CFG > "${LOGBASE}.eval.log" 2>&1
EVRC=$?
echo "[$(date)] [GPU $GPU] eval exit=$EVRC"
if [ $EVRC -ne 0 ]; then
    echo "[$(date)] eval failed — last 30 lines of ${LOGBASE}.eval.log:"
    tail -30 "${LOGBASE}.eval.log"
    exit $EVRC
fi

CSV=/home/ks2218/la-proteina/inference/results_${CFG}_0.csv
echo "[$(date)] === HYBRID probe done: $CFG ==="
if [ -f "$CSV" ]; then
    echo "Results CSV: $CSV"
    echo
    $PYTHON_EXEC -c "
import pandas as pd
df = pd.read_csv('$CSV')
sc = [c for c in df.columns if 'scrmsd' in c.lower() and 'all' not in c.lower()]
df['_best'] = df[sc].min(axis=1)
df = df[df['_best'] > 0]
print('Designability summary (best-scRMSD-per-sample < 2 Å, sentinels dropped):')
print(df.groupby('L').agg(n=('_best','size'), designable=('_best', lambda s: int((s<2).sum())), median=('_best','median'), best=('_best','min'), worst=('_best','max')).round(2).to_string())
print()
print('Pooled: {}/{} = {:.1f}%'.format(int((df['_best']<2.0).sum()), len(df), 100*(df['_best']<2.0).mean()))
"
else
    echo "Expected CSV not found at $CSV — inspect ${LOGBASE}.eval.log."
fi
