"""Content-free K-schedule sweep on the lower-half-sparse architecture.

Each schedule is a list of K_total per layer (one entry per sparse lower layer).
The driver translates each K to (n_seq, n_spatial, n_random) via a fixed
decomposition, writes a per-schedule YAML inheriting from
inference_layer_sel_base, then runs generate.py + evaluate.py via subprocess.

Schedules whose results CSV already exists are skipped (per feedback memory).

Usage (nohup'd; runs sequentially on the GPU set by CUDA_VISIBLE_DEVICES):
    CUDA_VISIBLE_DEVICES=0 \\
    PYTHON_EXEC=/home/ks2218/.conda/envs/laproteina_env/bin/python \\
    nohup /home/ks2218/.conda/envs/laproteina_env/bin/python \\
        script_utils/schedule_sweep.py > nohup_schedule_sweep.log 2>&1 &

To run a subset, pass schedule names as args:
    ... schedule_sweep.py hourglass_sharp lambda_middle
"""
import os
import subprocess
import sys
import time
from pathlib import Path

REPO = Path("/home/ks2218/la-proteina")
PY = os.environ.get("PYTHON_EXEC",
                    "/home/ks2218/.conda/envs/laproteina_env/bin/python")

# (name, [K_total per sparse lower layer 0..6])
# All target mean K ≈ 40 (sum ~ 280) with K[0] ≥ 32 (early-starvation rule
# from E091 increasing-ramp failure) and varied shapes.
SCHEDULES = [
    ("hourglass_sharp",      [56, 48, 32, 16, 32, 48, 56]),  # sum 288
    ("hourglass_smooth",     [48, 40, 32, 24, 32, 40, 48]),  # sum 264
    ("lambda_middle",        [32, 40, 48, 56, 48, 40, 32]),  # sum 296
    ("sine_middle",          [40, 44, 48, 52, 48, 44, 40]),  # sum 316
    ("cosine_boundaries",    [52, 44, 40, 32, 40, 44, 52]),  # sum 304
    ("alternating_56_24",    [56, 24, 56, 24, 56, 24, 56]),  # sum 296
    ("spike_middle",         [40, 40, 40, 64, 40, 40, 40]),  # sum 304
    ("front_heavy_step",     [64, 56, 32, 32, 32, 32, 32]),  # sum 280
    ("continuous_decreasing",[56, 48, 40, 40, 32, 32, 32]),  # sum 280
]

# K-total → (n_seq, n_spatial, n_random) with K = 2*n_seq + n_spatial + n_random.
# Matches existing canonical splits at K=40 (8,8,16) and K=64 (8,16,32) so a
# K=40 entry in a schedule produces the same K-set the K=40 baseline used.
K_DECOMP = {
    8:  (2,  2,  2),
    16: (4,  4,  4),
    24: (4,  4, 12),
    32: (4,  8, 16),
    40: (8,  8, 16),  # canonical K=40 SALAD
    44: (8, 12, 16),
    48: (8, 12, 20),
    52: (8, 12, 24),
    56: (8, 16, 24),
    64: (8, 16, 32),  # canonical K=64 SALAD
}


def k_to_split(K: int):
    if K in K_DECOMP:
        return K_DECOMP[K]
    # Generic fallback (won't be hit by the listed schedules; defensive).
    n_seq = max(4, K // 4)
    rem = K - 2 * n_seq
    n_sp = max(0, rem // 2)
    n_rd = rem - n_sp
    return (n_seq, n_sp, n_rd)


MASK_LOWER_HALF = ("[true, true, true, true, true, true, true, "
                   "false, false, false, false, false, false, false]")


def write_yaml(name: str, k_list, config_name: str) -> Path:
    splits = [k_to_split(k) for k in k_list]
    sum_k = sum(k_list)
    mean_k = sum_k / len(k_list)
    body = [
        f"# Auto-generated by schedule_sweep.py. Schedule: {name}",
        f"# Per-layer K-totals: {k_list}",
        f"# Sum {sum_k}, mean {mean_k:.1f} (K=40 budget reference: sum=280).",
        "defaults:",
        "  - inference_layer_sel_base",
        "  - _self_",
        "",
        f"config_name: {config_name}",
        "",
        "generation:",
        "  args:",
        f"    layer_sparse_mask: {MASK_LOWER_HALF}",
        "    n_seq_neighbors_override: 8",
        "    n_spatial_neighbors_override: 8",
        "    n_random_neighbors_override: 16",
        "    layer_K_splits:",
    ]
    for s, k in zip(splits, k_list):
        body.append(f"      - [{s[0]}, {s[1]}, {s[2]}]   # K={k}")
    body += [
        "  dataset:",
        "    nsamples: 12",
        "    max_nsamples_per_batch: 6",
        "    nlens_cfg:",
        "      nres_lens: [50, 100, 200]",
        "",
    ]
    path = REPO / "configs" / f"{config_name}.yaml"
    path.write_text("\n".join(body))
    return path


def csv_present(config_name: str) -> bool:
    return any((REPO / "inference").glob(f"results_{config_name}_*.csv"))


def output_dir(config_name: str) -> Path:
    return REPO / "inference" / config_name


def run_one(name: str, k_list) -> str:
    config_name = f"inference_layer_sel_schedule_{name}_n12"
    if csv_present(config_name):
        print(f"[skip] {name}: results_{config_name}_*.csv already exists",
              flush=True)
        return "skipped"

    # Defensive clean of stale output dir (would block evaluate.py).
    od = output_dir(config_name)
    if od.exists():
        import shutil
        shutil.rmtree(od)

    write_yaml(name, k_list, config_name)
    sum_k = sum(k_list); mean_k = sum_k / len(k_list)
    print(f"\n=== START {name}: K={k_list} sum={sum_k} mean={mean_k:.1f} ===",
          flush=True)

    env = dict(os.environ)
    env["PYTHON_EXEC"] = PY
    env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

    t0 = time.time()
    r = subprocess.run([PY, "proteinfoundation/generate.py",
                        "--config-name", config_name],
                       cwd=REPO, env=env)
    if r.returncode != 0:
        print(f"[FAIL gen] {name} returncode={r.returncode}", flush=True)
        return "fail_gen"
    print(f"[gen] {name} done in {time.time()-t0:.0f}s", flush=True)

    t0 = time.time()
    r = subprocess.run([PY, "proteinfoundation/evaluate.py",
                        "--config_name", config_name],
                       cwd=REPO, env=env)
    if r.returncode != 0:
        print(f"[FAIL eval] {name} returncode={r.returncode}", flush=True)
        return "fail_eval"
    print(f"[eval] {name} done in {time.time()-t0:.0f}s", flush=True)

    # Quick per-L designable summary so the milestone log is informative.
    import pandas as pd
    csvs = sorted((REPO / "inference").glob(f"results_{config_name}_*.csv"))
    if csvs:
        df = pd.read_csv(csvs[-1])
        parts = []
        for L in sorted(df["L"].unique()):
            sub = df[df["L"] == L]
            s = sub["_res_scRMSD_ca_esmfold"]
            d = int(((s < 2.0) & s.notna() & (s > 0)).sum())
            parts.append(f"L={L}:{d}/{len(sub)}")
        print(f"[DONE] {name}  " + "  ".join(parts), flush=True)
    else:
        print(f"[DONE] {name}  (no CSV found?)", flush=True)
    return "ok"


def main():
    requested = set(sys.argv[1:])
    to_run = SCHEDULES if not requested else [
        (n, k) for (n, k) in SCHEDULES if n in requested
    ]
    if requested and not to_run:
        sys.exit(f"No matching schedule for {sorted(requested)}; "
                 f"choices: {[n for n,_ in SCHEDULES]}")
    print(f"=== schedule_sweep: {len(to_run)} schedules, "
          f"GPU env CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES','?')} ===",
          flush=True)
    statuses = []
    for name, k_list in to_run:
        s = run_one(name, k_list)
        statuses.append((name, s))
    print("\n=== ALL SCHEDULES PROCESSED ===")
    for n, s in statuses:
        print(f"  {n}: {s}")


if __name__ == "__main__":
    main()
