"""N=30 extension of the top schedules from E094 / E096.

Bumps N from 12 → 30 (per-L) on the 4 best content-free schedules to tighten
statistics for the Finding write-up. Output goes to new configs with `_n30`
suffix so existing `_n12` CSVs are preserved (per don't-rerun-existing memory).

Reuses K_DECOMP, k_to_split, csv_present from schedule_sweep.py; writes its
own YAML (custom nsamples).
"""
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path("/home/ks2218/la-proteina")
sys.path.insert(0, str(REPO / "script_utils"))

from schedule_sweep import K_DECOMP, k_to_split, csv_present  # noqa: E402

# Top 4 from E094 / E096 N=12 sweeps.
SCHEDULES = [
    ("front_plateau_then_taper", [56, 56, 56, 40, 32, 24, 16]),  # 22/36 best
    ("sine_middle",              [40, 44, 48, 52, 48, 44, 40]),  # 22/36 tied
    ("mirror_decreasing",        [64, 56, 48, 40, 32, 24, 16]),  # 20/36, mean K=40
    ("continuous_decreasing",    [56, 48, 40, 40, 32, 32, 32]),  # 20/36, mean K=40
]

NSAMPLES = 30
MAX_PER_BATCH = 6

MASK_LOWER_HALF = ("[true, true, true, true, true, true, true, "
                   "false, false, false, false, false, false, false]")


def write_yaml(name, k_list, config_name):
    splits = [k_to_split(k) for k in k_list]
    sum_k = sum(k_list); mean_k = sum_k / len(k_list)
    body = [
        f"# Auto-generated by schedule_sweep_n30.py. Schedule: {name} (N={NSAMPLES} extension of N=12).",
        f"# Per-layer K-totals: {k_list}",
        f"# Sum {sum_k}, mean {mean_k:.1f}.",
        "defaults:",
        "  - inference_layer_sel_base",
        "  - _self_",
        "",
        f"config_name: {config_name}",
        "",
        "generation:",
        "  args:",
        f"    layer_sparse_mask: {MASK_LOWER_HALF}",
        "    n_seq_neighbors_override: 8",
        "    n_spatial_neighbors_override: 8",
        "    n_random_neighbors_override: 16",
        "    layer_K_splits:",
    ]
    for s, k in zip(splits, k_list):
        body.append(f"      - [{s[0]}, {s[1]}, {s[2]}]   # K={k}")
    body += [
        "  dataset:",
        f"    nsamples: {NSAMPLES}",
        f"    max_nsamples_per_batch: {MAX_PER_BATCH}",
        "    nlens_cfg:",
        "      nres_lens: [50, 100, 200]",
        "",
    ]
    path = REPO / "configs" / f"{config_name}.yaml"
    path.write_text("\n".join(body))
    return path


def run_one(name, k_list):
    config_name = f"inference_layer_sel_schedule_{name}_n{NSAMPLES}"
    if csv_present(config_name):
        print(f"[skip] {name}: results_{config_name}_*.csv already exists",
              flush=True)
        return "skipped"
    od = REPO / "inference" / config_name
    if od.exists():
        shutil.rmtree(od)
    write_yaml(name, k_list, config_name)
    print(f"\n=== START {name} (N={NSAMPLES}): K={k_list} sum={sum(k_list)} ===",
          flush=True)
    env = dict(os.environ)
    env["PYTHON_EXEC"] = os.environ.get(
        "PYTHON_EXEC", "/home/ks2218/.conda/envs/laproteina_env/bin/python")
    env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
    PY = env["PYTHON_EXEC"]

    t0 = time.time()
    r = subprocess.run([PY, "proteinfoundation/generate.py",
                        "--config-name", config_name],
                       cwd=REPO, env=env)
    if r.returncode != 0:
        print(f"[FAIL gen] {name} returncode={r.returncode}", flush=True)
        return "fail_gen"
    print(f"[gen] {name} done in {time.time()-t0:.0f}s", flush=True)

    t0 = time.time()
    r = subprocess.run([PY, "proteinfoundation/evaluate.py",
                        "--config_name", config_name],
                       cwd=REPO, env=env)
    if r.returncode != 0:
        print(f"[FAIL eval] {name} returncode={r.returncode}", flush=True)
        return "fail_eval"
    print(f"[eval] {name} done in {time.time()-t0:.0f}s", flush=True)

    import pandas as pd, glob
    csvs = sorted(glob.glob(str(REPO / "inference"
                                  / f"results_{config_name}_*.csv")))
    if csvs:
        df = pd.read_csv(csvs[-1])
        parts = []
        for L in sorted(df["L"].unique()):
            sub = df[df["L"] == L]
            s = sub["_res_scRMSD_ca_esmfold"]
            d = int(((s < 2.0) & s.notna() & (s > 0)).sum())
            parts.append(f"L={L}:{d}/{len(sub)}")
        print(f"[DONE] {name} (N={NSAMPLES})  " + "  ".join(parts), flush=True)
    return "ok"


def main():
    requested = set(sys.argv[1:])
    to_run = SCHEDULES if not requested else [
        s for s in SCHEDULES if s[0] in requested
    ]
    if requested and not to_run:
        sys.exit(f"No match for {sorted(requested)}; "
                 f"choices: {[s[0] for s in SCHEDULES]}")
    print(f"=== schedule_sweep_n30: {len(to_run)} schedules @ N={NSAMPLES}, "
          f"GPU env CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES','?')} ===",
          flush=True)
    statuses = []
    for name, k_list in to_run:
        s = run_one(name, k_list)
        statuses.append((name, s))
    print(f"\n=== ALL N={NSAMPLES} SCHEDULES PROCESSED ===")
    for n, s in statuses:
        print(f"  {n}: {s}")


if __name__ == "__main__":
    main()
