"""Whole-model schedule sweep — vary BOTH the sparse/dense mask AND the per-
sparse-layer K. Tests where the minimum dense footprint sits.

Imports K_DECOMP and csv_present from schedule_sweep.py; writes its own YAML
(needs `layer_sparse_mask` AND `layer_K_splits`).
"""
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path("/home/ks2218/la-proteina")
sys.path.insert(0, str(REPO / "script_utils"))

from schedule_sweep import K_DECOMP, k_to_split, csv_present  # noqa: E402


# (name, mask_14bool, K_per_sparse_layer)
# All 14 layers; True=sparse, False=dense.
# K_per_sparse_layer length must equal number of True in mask.
SCHEDULES = [
    # 11 sparse (layers 0-10), 3 dense (11, 12, 13). Front-heavy then rising
    # toward dense boundary.
    ("whole_3dense_end", [True]*11 + [False]*3,
     [56, 56, 56, 40, 32, 24, 16, 24, 32, 40, 56]),

    # Sparse [0-6], dense [7], sparse [8-13]. Two front-heavy sparse blocks
    # with one dense rescue between.
    ("whole_1dense_mid", [True]*7 + [False] + [True]*6,
     [56, 56, 56, 40, 32, 24, 16, 56, 48, 40, 32, 24, 16]),

    # Dense at positions 3, 7, 11, 13. Periodic dense checkpoints.
    # 10 sparse layers in groups of 3 (each a mini front-heavy) + 1 final sparse.
    ("whole_interleaved",
     [True, True, True, False, True, True, True, False, True, True, True, False, True, False],
     [56, 40, 32, 56, 40, 32, 56, 40, 32, 40]),

    # 14 sparse, no dense at all. U-shape K: high front, low middle, rising end.
    ("whole_all_sparse_U", [True]*14,
     [64, 64, 56, 40, 32, 24, 16, 16, 24, 40, 56, 64, 64, 64]),

    # 12 sparse (layers 0-11), 2 dense (12, 13). Front-heavy then rising
    # toward the very-end dense pair.
    ("whole_2dense_min", [True]*12 + [False]*2,
     [56, 56, 56, 40, 32, 24, 16, 16, 24, 32, 40, 56]),
]


def render_mask(mask):
    return "[" + ", ".join("true" if x else "false" for x in mask) + "]"


def write_yaml(name, mask, k_list, config_name):
    n_sparse = sum(mask)
    assert len(k_list) == n_sparse, (
        f"{name}: K_per_sparse_layer has {len(k_list)} entries but mask has "
        f"{n_sparse} sparse layers."
    )
    splits = [k_to_split(k) for k in k_list]
    sum_k = sum(k_list); mean_k = sum_k / len(k_list)
    body = [
        f"# Auto-generated by schedule_sweep_whole_model.py. Schedule: {name}",
        f"# Mask (T=sparse, F=dense): {mask}",
        f"# Per-sparse-layer K-totals: {k_list}",
        f"# Sum {sum_k}, mean per sparse layer {mean_k:.1f}.",
        "defaults:",
        "  - inference_layer_sel_base",
        "  - _self_",
        "",
        f"config_name: {config_name}",
        "",
        "generation:",
        "  args:",
        f"    layer_sparse_mask: {render_mask(mask)}",
        "    n_seq_neighbors_override: 8",
        "    n_spatial_neighbors_override: 8",
        "    n_random_neighbors_override: 16",
        "    layer_K_splits:",
    ]
    for s, k in zip(splits, k_list):
        body.append(f"      - [{s[0]}, {s[1]}, {s[2]}]   # K={k}")
    body += [
        "  dataset:",
        "    nsamples: 12",
        "    max_nsamples_per_batch: 6",
        "    nlens_cfg:",
        "      nres_lens: [50, 100, 200]",
        "",
    ]
    path = REPO / "configs" / f"{config_name}.yaml"
    path.write_text("\n".join(body))
    return path


def run_one(name, mask, k_list):
    config_name = f"inference_layer_sel_{name}_n12"
    if csv_present(config_name):
        print(f"[skip] {name}: results_{config_name}_*.csv already exists",
              flush=True)
        return "skipped"
    od = REPO / "inference" / config_name
    if od.exists():
        shutil.rmtree(od)
    write_yaml(name, mask, k_list, config_name)
    sum_k = sum(k_list)
    n_sparse = sum(mask); n_dense = len(mask) - n_sparse
    print(f"\n=== START {name}: {n_sparse} sparse / {n_dense} dense, "
          f"K_per_sparse={k_list} sum={sum_k} ===", flush=True)
    env = dict(os.environ)
    env["PYTHON_EXEC"] = os.environ.get(
        "PYTHON_EXEC", "/home/ks2218/.conda/envs/laproteina_env/bin/python")
    env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
    PY = env["PYTHON_EXEC"]

    t0 = time.time()
    r = subprocess.run([PY, "proteinfoundation/generate.py",
                        "--config-name", config_name],
                       cwd=REPO, env=env)
    if r.returncode != 0:
        print(f"[FAIL gen] {name} returncode={r.returncode}", flush=True)
        return "fail_gen"
    print(f"[gen] {name} done in {time.time()-t0:.0f}s", flush=True)

    t0 = time.time()
    r = subprocess.run([PY, "proteinfoundation/evaluate.py",
                        "--config_name", config_name],
                       cwd=REPO, env=env)
    if r.returncode != 0:
        print(f"[FAIL eval] {name} returncode={r.returncode}", flush=True)
        return "fail_eval"
    print(f"[eval] {name} done in {time.time()-t0:.0f}s", flush=True)

    import pandas as pd, glob
    csvs = sorted(glob.glob(str(REPO / "inference"
                                  / f"results_{config_name}_*.csv")))
    if csvs:
        df = pd.read_csv(csvs[-1])
        parts = []
        for L in sorted(df["L"].unique()):
            sub = df[df["L"] == L]
            s = sub["_res_scRMSD_ca_esmfold"]
            d = int(((s < 2.0) & s.notna() & (s > 0)).sum())
            parts.append(f"L={L}:{d}/{len(sub)}")
        print(f"[DONE] {name}  " + "  ".join(parts), flush=True)
    return "ok"


def main():
    requested = set(sys.argv[1:])
    to_run = SCHEDULES if not requested else [
        s for s in SCHEDULES if s[0] in requested
    ]
    if requested and not to_run:
        sys.exit(f"No match for {sorted(requested)}; "
                 f"choices: {[s[0] for s in SCHEDULES]}")
    print(f"=== schedule_sweep_whole_model: {len(to_run)} schedules, "
          f"GPU env CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES','?')} ===",
          flush=True)
    statuses = []
    for name, mask, k_list in to_run:
        s = run_one(name, mask, k_list)
        statuses.append((name, s))
    print("\n=== ALL WHOLE-MODEL SCHEDULES PROCESSED ===")
    for n, s in statuses:
        print(f"  {n}: {s}")


if __name__ == "__main__":
    main()
