defaults:
  - inference_base
  - generation: uncond_codes_ca_only
  - _self_

run_name_: laproteina_ucond_notri_ca_only
ckpt_path: ./store/ca_only_diffusion_70M/checkpoints
ckpt_name: last.ckpt
autoencoder_ckpt_path:  # null — CA-only models have no AE
