#!/usr/bin/env bash
# Ablation sweep launched 2026-05-17 — fixt1 deployment recipe knobs.
# Twelve cells covering schedule timing, schedule shape, ensemble size,
# universal-guidance K-step denoising, and a clean-predictor mechanism cell.
# All cells: w=32, L=300, n=16 seeds, tango_min, denoised path, nsteps=400.
# Cell 12 is the exception: clean predictor + ensemble + L=300/400/500 × 16 seeds
# for paired comparison vs E066 NA-v1.
set -uo pipefail

ROOT=/home/ks2218/la-proteina
PY=/home/ks2218/.conda/envs/laproteina_env/bin/python
CFG_DIR=$ROOT/steering/config/ablation_2026_05_17
RESULTS_DIR=$ROOT/results/ablation_2026_05_17
LOG=$RESULTS_DIR/chain.log
SEEDS_16="42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57"

FIXT1=$ROOT/laproteina_steerability/logs/multitask_t1_noise_aware_fixt1/20260517_103256/checkpoints
CLEAN=$ROOT/laproteina_steerability/logs/multitask_t1/20260427_161809/checkpoints

mkdir -p "$CFG_DIR" "$RESULTS_DIR"

# fixt1 ensemble checkpoint list (5 folds) for inline use
FIXT1_ENS_LINES=$(for f in 0 1 2 3 4; do echo "    - $FIXT1/fold_${f}_best.pt"; done)
CLEAN_ENS_LINES=$(for f in 0 1 2 3 4; do echo "    - $CLEAN/fold_${f}_best.pt"; done)

write_cfg () {
  local name="$1"; local ckpt_block="$2"; local schedule="$3"; local denoise_steps="$4"
  cat > "$CFG_DIR/${name}.yaml" <<EOF
# Auto-generated by scripts/run_ablation_2026_05_17.sh
steering:
  enabled: true
$ckpt_block
  objectives:
    - property: tango
      direction: minimize
      weight: 1.0
  schedule:
$schedule
  gradient_norm: unit
  gradient_clip: 10.0
  channel: local_latents
  log_diagnostics: true
  denoising_steps: $denoise_steps
EOF
}

# --- Build all 12 configs ---

# fixt1 5-fold ensemble (used for cells 1-6 and 9-11)
ENS_CKPT="  checkpoint:
$FIXT1_ENS_LINES"

# fixt1 3-fold (folds ablation: 3 vs 5; 1-fold reading uses today's n=4 single-fold data, no rerun)
F3_CKPT="  checkpoint:
    - $FIXT1/fold_0_best.pt
    - $FIXT1/fold_1_best.pt
    - $FIXT1/fold_2_best.pt"

# clean predictor 5-fold ensemble (cell 12)
CLEAN_CKPT="  checkpoint:
$CLEAN_ENS_LINES"

# Schedules ----
BASELINE_SCHED='    type: linear_ramp
    w_max: 32.0
    t_start: 0.3
    t_end: 0.8
    t_stop: 0.9'

CONSTANT_ALL='    type: constant
    w_max: 32.0
    t_start: 0.0
    t_stop: 1.0'

LATE_ONLY='    type: linear_ramp
    w_max: 32.0
    t_start: 0.7
    t_end: 0.85
    t_stop: 0.95'

EARLY_ONLY='    type: linear_ramp
    w_max: 32.0
    t_start: 0.05
    t_end: 0.25
    t_stop: 0.4'

WIDE_RAMP='    type: linear_ramp
    w_max: 32.0
    t_start: 0.1
    t_end: 0.9
    t_stop: 1.0'

COSINE_SCHED='    type: cosine_ramp
    w_max: 32.0
    t_start: 0.3
    t_end: 0.8
    t_stop: 0.9'

CONSTANT_IN_WINDOW='    type: constant
    w_max: 32.0
    t_start: 0.3
    t_stop: 0.9'

write_cfg constant_all       "$ENS_CKPT" "$CONSTANT_ALL"       1
write_cfg late_only          "$ENS_CKPT" "$LATE_ONLY"          1
write_cfg early_only         "$ENS_CKPT" "$EARLY_ONLY"         1
write_cfg wide_ramp          "$ENS_CKPT" "$WIDE_RAMP"          1
write_cfg cosine             "$ENS_CKPT" "$COSINE_SCHED"       1
write_cfg constant_in_window "$ENS_CKPT" "$CONSTANT_IN_WINDOW" 1
write_cfg fold3              "$F3_CKPT"  "$BASELINE_SCHED"     1
write_cfg ug_K2              "$ENS_CKPT" "$BASELINE_SCHED"     2
write_cfg ug_K3              "$ENS_CKPT" "$BASELINE_SCHED"     3
write_cfg ug_K5              "$ENS_CKPT" "$BASELINE_SCHED"     5
write_cfg clean_ens_n48      "$CLEAN_CKPT" "$BASELINE_SCHED"   1

echo "[setup] configs written to $CFG_DIR" | tee -a "$LOG"

# --- Generation chain ---

cd "$ROOT"

run_cell () {
  local cell="$1"; local lengths="$2"; local seeds="$3"
  local outdir=$RESULTS_DIR/$cell
  if [ -d "$outdir/guided" ] && [ "$(ls "$outdir/guided"/*.pdb 2>/dev/null | wc -l)" -gt 0 ]; then
    echo "[skip] $cell already has output, skipping" | tee -a "$LOG"
    return
  fi
  mkdir -p "$outdir"
  echo "[gen $cell] $(date -Iseconds)" | tee -a "$LOG"
  $PY -m steering.generate \
    --proteina_config inference_ucond_notri_long \
    --steering_config steering/config/ablation_2026_05_17/${cell}.yaml \
    --lengths $lengths \
    --seeds $seeds \
    --output_dir results/ablation_2026_05_17/$cell \
    --device cuda:0 --skip_unguided 2>&1 | tee -a "$LOG"
}

# Iterative mode: GROUP env var selects which cells to run.
# GROUP=timing → 4 schedule-timing cells; GROUP=shape, GROUP=folds, GROUP=ug, GROUP=clean, GROUP=all
GROUP="${GROUP:-timing}"
echo "[group] running $GROUP" | tee -a "$LOG"

case "$GROUP" in
  timing)
    for cell in constant_all late_only early_only wide_ramp; do
      run_cell "$cell" "300" "$SEEDS_16"
    done ;;
  shape)
    for cell in cosine constant_in_window; do
      run_cell "$cell" "300" "$SEEDS_16"
    done ;;
  folds)
    for cell in fold3; do
      run_cell "$cell" "300" "$SEEDS_16"
    done ;;
  ug)
    for cell in ug_K2 ug_K3 ug_K5; do
      run_cell "$cell" "300" "$SEEDS_16"
    done ;;
  clean)
    run_cell clean_ens_n48 "300 400 500" "$SEEDS_16" ;;
  all)
    for cell in constant_all late_only early_only wide_ramp cosine constant_in_window \
                fold3 ug_K2 ug_K3 ug_K5; do
      run_cell "$cell" "300" "$SEEDS_16"
    done
    run_cell clean_ens_n48 "300 400 500" "$SEEDS_16" ;;
  *) echo "Unknown GROUP=$GROUP" >&2; exit 1 ;;
esac

# --- Eval ---

echo "[eval] $(date -Iseconds)" | tee -a "$LOG"
$PY $ROOT/scripts/eval_ablation_2026_05_17.py 2>&1 | tee -a "$LOG"

echo "ALL DONE $(date -Iseconds)" | tee -a "$LOG"
