"""fixt1 full replication of the NA-v1 property-steering experiments.

Runs every cell of E032/E066/E067/E068/net_charge_max/net_charge_min with the
fixt1 5-fold ensemble + denoised path + K=1 + canonical linear_ramp schedule.

Idempotent: skips cells whose output dir already has 48 PDBs and 48 codesign
rows. Single GPU (cuda:0), sequential.
"""
from __future__ import annotations
import json
import logging
import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path("/home/ks2218/la-proteina")
PY = "/home/ks2218/.conda/envs/laproteina_env/bin/python"

FIXT1_CKPTS = [
    f"/home/ks2218/la-proteina/laproteina_steerability/logs/multitask_t1_noise_aware_fixt1/20260517_103256/checkpoints/fold_{i}_best.pt"
    for i in range(5)
]
SEEDS = list(range(42, 58))
LENGTHS = [300, 400, 500]

CFG_ROOT = ROOT / "steering/config/fixt1_full_replication_2026_05_18"
OUT_ROOT = ROOT / "results/fixt1_full_replication_2026_05_18"

# (grid_dir, cell_name, objectives_list, w_max)
CELLS = []

def add_cell(grid, name, objs, w):
    CELLS.append((grid, f"{name}_w{w}", objs, w))

# E032 — F10 headline grid (skip w=1, w=2, w=4 per Pareto-frontier scoping 2026-05-18)
for w in [8, 16]:
    add_cell("E032_ensemble_sweep", "tango_min",
             [{"property": "tango", "direction": "minimize", "weight": 1.0}], w)
    add_cell("E032_ensemble_sweep", "camsol_max",
             [{"property": "camsol_intrinsic", "direction": "maximize", "weight": 1.0}], w)
# E066 — high-w scout
for w in [32, 48, 64, 128]:
    add_cell("E066_high_w", "tango_min",
             [{"property": "tango", "direction": "minimize", "weight": 1.0}], w)
    add_cell("E066_high_w", "camsol_max",
             [{"property": "camsol_intrinsic", "direction": "maximize", "weight": 1.0}], w)
# E067 — IUPred-max (skip w=16; expected weak for iupred)
for w in [32, 64, 128]:
    add_cell("E067_iupred_max", "iupred_max",
             [{"property": "iupred3_fraction_disordered", "direction": "maximize", "weight": 1.0}], w)
# E068 — combo (skip w=16)
for w in [32, 48, 64, 128]:
    add_cell("E068_combo_camsol_tango", "combo_camsol_tango",
             [{"property": "camsol_intrinsic", "direction": "maximize", "weight": 1.0},
              {"property": "tango", "direction": "minimize", "weight": 1.0}], w)
# net_charge_max (skip w=16)
for w in [32, 64, 128]:
    add_cell("net_charge_max_sweep", "net_charge_max",
             [{"property": "net_charge", "direction": "maximize", "weight": 1.0}], w)
# net_charge_min (skip w=16)
for w in [32, 64, 128]:
    add_cell("net_charge_min_sweep", "net_charge_min",
             [{"property": "net_charge", "direction": "minimize", "weight": 1.0}], w)


def write_config(yaml_path: Path, objectives: list, w_max: float):
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# fixt1 full replication — auto-generated by run_fixt1_full_replication.py",
        "steering:",
        "  enabled: true",
        "  checkpoint:",
    ]
    for ck in FIXT1_CKPTS:
        lines.append(f"    - {ck}")
    lines.append("  objectives:")
    for obj in objectives:
        lines.append(f"    - property: {obj['property']}")
        lines.append(f"      direction: {obj['direction']}")
        lines.append(f"      weight: {obj['weight']}")
    lines.extend([
        "  schedule:",
        "    type: linear_ramp",
        f"    w_max: {float(w_max)}",
        "    t_start: 0.3",
        "    t_end: 0.8",
        "    t_stop: 0.9",
        "  gradient_norm: unit",
        "  gradient_clip: 10.0",
        "  channel: local_latents",
        "  log_diagnostics: true",
        "  denoising_steps: 1",
        "",
    ])
    yaml_path.write_text("\n".join(lines))


def cell_complete(out_dir: Path, expected_n: int) -> bool:
    """A cell is complete if gen has all PDBs AND codesign has all rows."""
    guided = out_dir / "guided"
    if not guided.exists():
        return False
    n_pdbs = len(list(guided.glob("*.pdb")))
    cs_csv = out_dir / "codesign_guided.csv"
    if not cs_csv.exists():
        return False
    n_cs = sum(1 for _ in open(cs_csv)) - 1  # minus header
    return n_pdbs >= expected_n and n_cs >= expected_n


def run_cell(grid: str, cell: str, objectives: list, w_max: float):
    cfg = CFG_ROOT / grid / f"{cell}.yaml"
    out_dir = OUT_ROOT / grid / cell
    expected_n = len(SEEDS) * len(LENGTHS)

    write_config(cfg, objectives, w_max)

    if cell_complete(out_dir, expected_n):
        logging.info(f"[skip] {grid}/{cell} already complete ({expected_n} PDBs)")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    logging.info(f"[gen] {grid}/{cell} (w={w_max})")
    subprocess.run([
        PY, "-m", "steering.generate",
        "--proteina_config", "inference_ucond_notri_long",
        "--steering_config", str(cfg.relative_to(ROOT)),
        "--lengths", *[str(L) for L in LENGTHS],
        "--seeds", *[str(s) for s in SEEDS],
        "--output_dir", str(out_dir.relative_to(ROOT)),
        "--device", "cuda:0", "--skip_unguided",
    ], cwd=str(ROOT), check=False)

    logging.info(f"[codesign] {grid}/{cell}")
    subprocess.run([
        PY, "scripts/run_codesignability_sweep.py",
        "--lengths", *[str(L) for L in LENGTHS],
        "--seeds", *[str(s) for s in SEEDS],
        "--cfgs", cell,
    ], cwd=str(ROOT), env={**os.environ, "OUT_BASE": str((OUT_ROOT / grid).relative_to(ROOT))}, check=False)


def wait_for_clean_predictor():
    while True:
        try:
            out = subprocess.run(
                ["pgrep", "-af", "run_clean_ablation|clean_ens_n48"],
                capture_output=True, text=True,
            )
            if not out.stdout.strip():
                logging.info("Clean predictor finished; starting replication")
                return
            logging.info("Waiting for clean predictor to finish...")
        except Exception as e:
            logging.warning(f"pgrep failed: {e}")
            return
        time.sleep(60)


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(message)s",
        handlers=[
            logging.FileHandler(OUT_ROOT / "chain.log", mode="a"),
            logging.StreamHandler(sys.stdout),
        ],
    )
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    CFG_ROOT.mkdir(parents=True, exist_ok=True)

    logging.info(f"Total cells planned: {len(CELLS)}")
    logging.info(f"Expected PDBs per cell: {len(SEEDS) * len(LENGTHS)}")
    logging.info(f"Total PDBs expected: {len(CELLS) * len(SEEDS) * len(LENGTHS)}")

    wait_for_clean_predictor()

    t0 = time.time()
    for i, (grid, cell, objs, w) in enumerate(CELLS):
        logging.info(f"=== [{i+1}/{len(CELLS)}] {grid}/{cell} ===")
        run_cell(grid, cell, objs, w)
        elapsed = time.time() - t0
        rate = (i + 1) / max(elapsed, 1.0)
        remaining = (len(CELLS) - i - 1) / max(rate, 1e-6)
        logging.info(f"Elapsed: {elapsed/3600:.2f}h; ETA: {remaining/3600:.2f}h")

    logging.info("ALL_DONE_FULL_REPLICATION")


if __name__ == "__main__":
    main()
